# Exported from Render on 2025-03-16T02:55:22Z
services:
  - type: web
    name: ptcg-sim-meta
    runtime: node
    repo: https://github.com/Envoyofhell/ptcg-sim-meta
    plan: free
    envVars:
      - key: port
        sync: false
      - key: DATABASE_POSTGRES_URL
        sync: false
      - key: DATABASE_POSTGRES_URL_NO_SSL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SOCKET_ADMIN_PASSWORD
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    region: virginia
    buildCommand: pnpm install && mkdir -p database
    startCommand: node server.js
    rootDir: ./server
version: '1'
