# wrangler.toml
name = "ptcg-sim-meta"
compatibility_date = "2025-03-24"

[site]
bucket = "./client"
entry-point = "workers-site"

# Make sure to use double brackets for an array
[[d1_databases]]
binding = "DB"
database_name = "ptcg-sim-meta-db-test"
database_id = "YOUR_TEST_DATABASE_ID_HERE"

# Production environment configuration
[env.production]
routes = [
  { pattern = "test.meta-ptcg.org", custom_domain = true }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "ptcg-sim-meta-db"
database_id = "YOUR_PRODUCTION_DATABASE_ID_HERE"