name = "ptcg-sim-meta-dev"
main = "index.js"
compatibility_date = "2024-03-22"
compatibility_flags = ["nodejs_compat"]

# Development environment
[env.dev]
name = "ptcg-sim-meta-dev"
vars = { 
    ENVIRONMENT = "development",
    # Add any other development-specific variables
}

# Production environment
[env.production]
name = "ptcg-sim-meta"
vars = { 
    ENVIRONMENT = "production",
    # Add production-specific variables
}

# Additional configurations
[triggers]
crons = ["0 0 * * *"] # Run cleanup once per day at midnight UTC