# Comprehensive Wrangler Configuration for PTCG-Sim-Meta

# Basic Worker Metadata
name = "ptcg-sim-meta"
main = "dist/worker.js"
compatibility_date = "2025-03-22"
compatibility_flags = ["nodejs_compat"]

# Optimized Build Configuration
[build]
command = "node esbuild.config.js"
cwd = "."
watch_dir = ["src", "workers"]

# Global Routes Configuration
routes = [
  { pattern = "*ptcg-sim-meta.pages.dev/api/*", zone_name = "ptcg-sim-meta.pages.dev" },
  { pattern = "*ptcg-sim-meta.pages.dev/socket.io/*", zone_name = "ptcg-sim-meta.pages.dev" },
  { pattern = "meta-ptcg.org/api/*", zone_name = "meta-ptcg.org" },
  { pattern = "meta-ptcg.org/socket.io/*", zone_name = "meta-ptcg.org" }
]

# Periodic Maintenance Triggers
[triggers]
crons = [
  "0 0 * * *",      # Daily maintenance at midnight UTC
  "0 12 * * *"      # Additional midday check
]

# Development Environment Configuration
[env.dev]
name = "ptcg-sim-meta-dev"
workers_dev = true

# Development Environment Variables
[env.dev.vars]
  # Application Configuration
  ENVIRONMENT = "development"
  DEBUG_MODE = "true"
  LOG_LEVEL = "debug"
  WORKER_VERSION = "1.5.1"
  BUILD_TIMESTAMP = "" # Dynamically replaced during build
  API_BASE = "/api"
  SOCKET_PATH = "/socket.io"
  SOCKET_ENABLED = "true"

  # Performance and Security Optimizations
  RATE_LIMIT_WINDOW = "60"
  RATE_LIMIT_MAX_REQUESTS = "100"
  CACHE_CONTROL_MAX_AGE = "3600"

# Development Environment Performance Headers
[env.dev.headers]
  # Aggressive Caching for Static Assets
  [env.dev.headers."*.js"]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=60"
  [env.dev.headers."*.css"]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=60"
  [env.dev.headers."*.json"]
    Cache-Control = "public, max-age=300, stale-while-revalidate=60"

# Development Environment CORS Configuration
[env.dev.cors]
  allowed_origins = ["*"]
  allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers = [
    "Content-Type", 
    "Authorization", 
    "X-Requested-With", 
    "Upgrade", 
    "Connection"
  ]
  max_age = 86400

# Production Environment Configuration
[env.production]
name = "ptcg-sim-meta"
workers_dev = false

# Production Environment Variables
[env.production.vars]
  # Application Configuration
  ENVIRONMENT = "production"
  DEBUG_MODE = "false"
  LOG_LEVEL = "info"
  WORKER_VERSION = "1.5.1"
  BUILD_TIMESTAMP = "" # Dynamically replaced during build
  API_BASE = "/api"
  SOCKET_PATH = "/socket.io"
  SOCKET_ENABLED = "true"

  # Performance and Security Optimizations
  RATE_LIMIT_WINDOW = "60"
  RATE_LIMIT_MAX_REQUESTS = "50"
  CACHE_CONTROL_MAX_AGE = "86400"

# Production Environment Performance Headers
[env.production.headers]
  # Strict Caching for Static Assets
  [env.production.headers."*.js"]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=3600"
  [env.production.headers."*.css"]
    Cache-Control = "public, max-age=86400, stale-while-revalidate=3600"
  [env.production.headers."*.json"]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=600"

# Production Environment CORS Configuration
[env.production.cors]
  allowed_origins = [
    "https://meta-ptcg.org",
    "https://www.meta-ptcg.org"
  ]
  allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers = [
    "Content-Type", 
    "Authorization", 
    "X-Requested-With", 
    "Upgrade", 
    "Connection"
  ]
  max_age = 86400

# Additional Optimization Configurations
[placement]
mode = "smart"

# Experimental Features (Use with caution)
[experimental]
# Enable new runtime features if available
enable_preview = true