name = "ptcg-sim-meta-dev"
main = "index.js"
compatibility_date = "2025-03-22"
compatibility_flags = ["nodejs_compat"]

# Development environment
[env.dev]
name = "ptcg-sim-meta-dev"
vars = { 
    ENVIRONMENT = "development",
    LOG_LEVEL = "debug"
}

# Production environment
[env.production]
name = "ptcg-sim-meta"
vars = { 
    ENVIRONMENT = "production", 
    LOG_LEVEL = "info"
}

[triggers]
crons = ["0 0 * * *"] # Run cleanup once per day at midnight UTC