name = "ptcg-sim-meta-dev"
main = "index.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# Development environment
[env.dev]
name = "ptcg-sim-meta-dev"
vars = { ENVIRONMENT = "development" }  # Properly closed inline table

# Production environment
[env.production]
name = "ptcg-sim-meta"
vars = { ENVIRONMENT = "production" }

# Other configurations remain the same
[triggers]
crons = ["0 0 * * *"] # Run cleanup once per day at midnight UTC