# Enhanced wrangler.toml for PTCG-Sim-Meta
# This configuration sets up both the Cloudflare Worker and Page deployments

# Basic Worker metadata
name = "ptcg-sim-meta"  # Unique name for your Cloudflare Worker
main = "index.js"       # Entry point of your Worker
compatibility_date = "2025-03-22"  # Locks in specific runtime features
compatibility_flags = ["nodejs_compat"]  # Enable Node.js compatibility mode

# Worker routes configuration
# This tells Cloudflare which requests should be handled by your worker
[routes]
pattern = "*ptcg-sim-meta.pages.dev/*"
zone_name = "ptcg-sim-meta.pages.dev"

# Content type headers for proper MIME types
# This fixes the "Failed to load module script" error
[headers]
  [headers."*.js"]
    Content-Type = "application/javascript"
  [headers."*.mjs"]
    Content-Type = "application/javascript"
  [headers."*.css"]
    Content-Type = "text/css"
  [headers."*.json"]
    Content-Type = "application/json"

# CORS configuration for proper API access
[cors]
  allowed_origins = ["*"]
  allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers = ["Content-Type", "Authorization", "X-Requested-With", "Upgrade", "Connection"]
  max_age = 86400

# Enhanced environment variables for dev environment
[env.dev]
name = "ptcg-sim-meta-dev"
ENVIRONMENT = "development"
LOG_LEVEL = "debug"
SOCKET_ENABLED = "true"

# Production environment configuration
[env.production]
name = "ptcg-sim-meta"
ENVIRONMENT = "production"
LOG_LEVEL = "info"
SOCKET_ENABLED = "true"

# Build configuration (for worker only)
[build]
command = "pnpm run build"  # Use this for the Worker build
cwd = "workers"             # Build in the workers directory
dest = "dist"               # Output to the dist directory

# Scheduled tasks for maintenance operations
[triggers]
crons = ["0 0 * * *"]      # Run maintenance daily at midnight UTC